// Auto-generated by some MotherTode
(() => {

			const global = window
			const scope = {}
			const term = (() => {
	global.EWATode = Term.term('EWATode', scope)
	return Term.subTerms(Term.string(''), [['EWATode', Term.string(`Hello world!`)]])
})()
			for (const key in term) {
				scope[key] = term[key]
			}
			return term
		
})()